name: appgym
description: "AppGym -- entrenador personal inteligente para gimnasio."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.2
  intl: ^0.19.0
  google_fonts: ^8.1.0
  drift: ^2.34.0
  drift_flutter: ^0.3.0
  flutter_3d_controller: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.1+1
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/exercises.json
    - assets/models_3d/
